### ISSUE TITLE
Failure on apostrophe

### ISSUE THREAD

**Issue by mmmmmrob** [sjmeverett/promised-csv#2]
Parsing of CSV with apostrophe causes error:

`E05000082,St Michael's,E92000001`

This seems to be valid, and is parsed by other CSV libraries. It fails under promised-csv with

`````` events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Line 0 is not valid.
    at /app/node_modules/promised-csv/index.js:37:19
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)```
``````

**Comment by ZephD** [comment]
Also having this trouble. Should automatically escape the character.
